FROM node:23-alpine

# Set working directory
WORKDIR /app

# Copy dependency files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the frontend code
COPY . .

# Build the React app
RUN npm run build

# Install `serve` to serve the static build
RUN npm install -g serve

# Expose the default port
EXPOSE 5173

CMD [ "serve", "-s", "dist" ]
