
services:
  mongodb:
    image: jagritchawla/panscience-db:latest
    container_name: mongo_db
    ports:
      - "27017:27017"    # port mapping
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db
    network_mode: "host"
  
  frontend:
    image: jagritchawla/panscience-frontend:latest
    container_name: panscience_frontend
    ports:
      - "5173:3000"    # port mapping
  
  backend:
    image: jagritchawla/panscience-backend:latest
    container_name: panscience_backend
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    network_mode: "host"


volumes:
  mongo-data: